@startuml
start
:Покупатель;
:Корзина;
:Система управления товарами;
:Система инвентаризации;

repeat
  :Добавить товар;
  :Обновить состав корзины;
  if (Товар в наличии?) then (Да)
    :Проверить фактическое наличие;
    if (Товар в наличии?) then (Да)
      :Подтвердить добавление товара;
    else (Нет)
      :Уведомить об отсутствии товара;
    endif
  else (Нет)
    :Уведомить об отсутствии товара;
  endif
repeat while (Покупатель желает добавить еще товар?);

:Удалить товар;
:Обновить состав корзины;

repeat
  :Изменить количество товара;
  :Обновить состав корзины;
repeat while (Покупатель желает изменить количество товара?);

stop
@enduml
