@startuml

if (Email найден в системе?) then (да)  fork
    :Пользователь вводит e-mail;    if (Ссылка действительна?) then (да)
      :Система отправляет письмо;      :Пользователь переходит по ссылке в письме;
      if (Новый пароль соответствует требованиям?) then (да)        :Пользователь устанавливает новый пароль;
      else (нет)        :Уведомление о неверном пароле;
        stop
        endif
    else (нет)      :Уведомление о недействительной ссылке;
      stop
      endif
  fork again    :Пользователь вводит номер телефона;
    if (Код из SMS верен?) then (да)      :Система отправляет SMS с кодом;
      :Пользователь вводит код из SMS;      if (Новый пароль соответствует требованиям?) then (да)
        :Пользователь устанавливает новый пароль;      else (нет)
        :Уведомление о неверном пароле;        stop
      endif    else (нет)
      :Уведомление о неверном коде;      stop
    endif  fork again
    :Пользователь вводит имя пользователя;    if (Ответ на секретный вопрос верен?) then (да)
      :Система задает секретный вопрос;      :Пользователь отвечает на вопрос;
      if (Новый пароль соответствует требованиям?) then (да)        :Пользователь устанавливает новый пароль;
      else (нет)        :Уведомление о неверном пароле;
        stop      endif
    else (нет)      :Уведомление о неверном ответе;
      stop    endif
  end fork  :Система сохраняет новый пароль;
  :Пользователь получает уведомление об успешном обновлении пароля;else (нет)
  :Уведомление о том, что email не найден;
  endif
stop
@enduml
