@startuml
start

:Администратор запускает настройку автоотказа;
:Администратор выбирает тип логики (новая или старая);
if (Старая логика?) then (yes)
  :Администратор задает параметр "cronTimer" (в днях);
  :Система запускает автоотказ с использованием cronTimer (периодичность в днях);
else (no)
  :Администратор задает параметр "Периодичность запуска" (в секундах);
  :Система запускает автоотказ с использованием fixedDelay (периодичность в секундах);
endif

stop
@enduml
