@startuml
start
:Готов к подписанию;
:Автовалидация;
if () then (Автовалидация успешна)
  :Документ отправлен;
    if () then (Документ подписан)
      :Документ успешно подписан;
      stop
    else (Документ НЕ подписан)
      :Обнаружена ошибка подписания;
      note right
        Требуется подписать повторно
      end note
    if () then (Повторная подпись
    требуется)
      '--> [Да] Готов к подписанию'
    else (Повторная подпись
    НЕ требуется)
    stop
    endif
endif
else (Автовалидация неуспешна)
  :Ошибка автовалидации;
    note right
      Проверьте заполнение полей
    end note
    if () then (Исправлено вручную)
      '--> [Да] Готов к подписанию'
    else (Исправлено как-то иначе?)
    stop
    endif
endif
:--> [Да] Готов к подписанию;
stop
@enduml