@startuml


[*] --> ЗаказСоздан : Новый заказ

state ЗаказСоздан {
    [*] --> ПроверкаОплаты
    ПроверкаОплаты --> ОплатаПринята : Оплата успешна
    ПроверкаОплаты --> ОплатаОтклонена : Оплата не прошла
}

ОплатаПринята --> Упаковка : Начало упаковки
Упаковка --> Доставка : Отправка товара
Доставка --> ЗаказДоставлен : Доставлено

ОплатаОтклонена --> [*] : Завершение заказа

ЗаказДоставлен --> [*] : Заказ завершён
@enduml
