@startuml
left to right direction
skinparam packageStyle rectangle

actor "Пользователь" as User
actor "Риэлтор" as Realtor
actor "Администратор" as Admin

rectangle "Прототип оператора прогнозирования цен на недвижимость" {
    User --> (Получение прогноза цены)
    Realtor --> (Добавление информации о недвижимости)
    Realtor --> (Просмотр прогнозов цен)
    Admin --> (Управление пользователями)

    (Просмотр прогнозов цен) --> (Получение прогноза цены) : include
    (Добавление информации о недвижимости) --> (Просмотр прогнозов цен) : extend

    User --> (Управление пользователями) : extends
    Realtor --> (Управление пользователями) : extends

    note left of (Получение прогноза цены)
      Пользователь запрашивает прогноз цены
    end note

    note right of (Добавление информации о недвижимости)
      Риэлтор добавляет информацию о недвижимости
    end note

    note right of (Просмотр прогнозов цен)
      Риэлтор просматривает прогнозы цен
    end note

    note right of (Управление пользователями)
      Администратор управляет пользователями
    end note
}
@enduml
